HEIGHT = 5
WIDTH = 5

descriptions=["Christmas presents under tree",
                "Santas Elf",
                "Santa in sleigh flying over a town delivering gifts on christmas eve",
                "candy cane on an christmas tree",
                "a festive robin redbreast",
                "a snowman with carrot nose and presents",
                "fairy on top of a christmas tree",
                "children playing with christmas presents",
                "christmas lunch",
                "christmas carol singers", 
                "christmas bells in a christmas tree",
                "rudolph the red nosed reindeer",
                "Santa in sleigh",
                "two snowmen with presents", 
                "snowy village scene",
                "christmas decoration",
                "christmas bells",
                "christmas snowflake",
                "christmas pudding with custard",
                "christmas feast with turkey",
                "father christmas laughing", 
                "christmas baby in a manger",
                "christmas mulled wine",
                "children enjoying playing with a new toy train",
                ]

gifts=[('8 python cheat sheets','https://blog.finxter.com/python-cheat-sheets/'),
('the finxter academy','https://academy.finxter.com/'),
('the finxter app','https://app.finxter.com/learn/computer/science/'),
('the finxster freelancer course','https://finxter.gumroad.com/l/python-freelancer/'),
('The Ultimate Guide to Start Learning Python','https://blog.finxter.com/start-learning-python/'),
('Coffee Break Numpy book','https://www.amazon.com/gp/product/B07WHB8FWC/ref=as_li_tl?ie=UTF8&tag=finxter-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B07WHB8FWC&linkId=447a5019492081d1b2892d9470bb29fc'),
('Leaving the Rat Race with Python book','https://www.amazon.com/Leaving-Rat-Race-Python-Developing-ebook/dp/B08G1XLDNB/ref=sr_1_5?qid=1670149592&refinements=p_27%3AChristian+Mayer&s=digital-text&sr=1-5&text=Christian+Mayer'),
('Coffee break Python book','https://www.amazon.com/Coffee-Break-Python-Kickstart-Understanding-ebook/dp/B07GSTJPFD/ref=sr_1_4?qid=1670149592&refinements=p_27%3AChristian+Mayer&s=digital-text&sr=1-4&text=Christian+Mayer'),
('Coffee Break Python Slicing','https://www.amazon.com/Coffee-Break-Python-Slicing-Workouts-ebook/dp/B07KSHLLG5/ref=sr_1_8?qid=1670149592&refinements=p_27%3AChristian+Mayer&s=digital-text&sr=1-8&text=Christian+Mayer'),
('Coffee Break Pandas','https://www.amazon.com/Coffee-Break-Pandas-Puzzles-Superpower-ebook/dp/B08NG8QHW7/ref=sr_1_9?qid=1670149592&refinements=p_27%3AChristian+Mayer&s=digital-text&sr=1-9&text=Christian+Mayer'),
('',''),
]

